add the ability to clone to non-shared storage on different nodes
bpg/terraform-provider-proxmox pull request #178
Opened 2022-12-09 21:19 UTC by wbpascal

### Introduction

As mentioned in various different forum posts on places like the Proxmox forums (e.g. https://forum.proxmox.com/threads/500-cant-clone-to-non-shared-storage-local.49078/#post-229727), the Promox API currently does not support using the Clone API to clone a VM to a different node if the target datastore is non-shared. The above forum post also mentions a workaround, which can be used to circumvent this limitation which is to first clone the VM to the local node (with a non-shared datastore) and then migrate it to the target node and datastore using the Migrate API.

I have added this workaround to the provider under the specific condition that the user wants to clone a VM to a different node than the source node and the target datastore is non-shared. Because we first have to clone the VM to the source node, I have also added a new argument `temp_datastore_id` to the `clone` block. In this argument, the user can enter the local datastore on the source VM to which the VM is cloned in the first step before migration.

Please be aware that this is my first time writing code in Go, so I am happy for any ideas and suggestions for improvements.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

2022-12-09 22:36 UTC, bpg commented
Awesome! Thanks for the PR @wbpascal, I'll review it in the next few days.

2022-12-10 19:30 UTC, bpg requested changes
Great work @wbpascal! I like the comments in the code, and the way you structured it. The provider's code base is not the best to work with, but that's what we have.

I can't really test this change on multiple nodes, as I don't have a clustered PVE in my lab, but my test on a single node has failed. Can you please take a look at my comments to the PR?

2022-12-10 19:30 UTC, bpg-dev commented on proxmox/virtual_environment_vm.go
> +// MigrateVMAsync migrates a virtual machine.
```suggestion
// MigrateVM migrates a virtual machine.
```

2022-12-10 19:30 UTC, bpg-dev commented on proxmoxtf/resource_virtual_environment_vm.go
> +						mkResourceVirtualEnvironmentVMCloneTempDatastoreID: {
Could you pls add the new argument to the doc?
https://github.com/bpg/terraform-provider-proxmox/blob/main/docs/resources/virtual_environment_vm.md

2022-12-10 19:30 UTC, bpg-dev commented on proxmox/virtual_environment_datastores.go
> +// ListDatastoreFiles gets status information for a given datastore.
```suggestion
// GetDatastoreStatus gets status information for a given datastore.
```

2022-12-10 19:30 UTC, bpg-dev commented on proxmoxtf/resource_virtual_environment_vm.go
> +	datastoreStatus, err := veClient.GetDatastoreStatus(ctx, cloneNodeName, cloneDatastoreID)
If `cloneNodeName` is empty the `veClient.GetDatastoreStatus` call will fail. I would leave the `if` statement that was here before and put the logic under it. This will also allow to remove duplicate condition on lines 1189 and 1196.
I.e.
```go
if cloneNodeName != "" && cloneNodeName != nodeName {
...
    if cloneDatastoreShared {
      // simple clone here
    } else {
      // clone to temp then migrate
    }
} else {
    // simple clone on the same node
}
```

2022-12-10 19:30 UTC, bpg commented on proxmoxtf/resource_virtual_environment_vm.go
> +		if err != nil {
Just a small style thing, I would keep error check right on the next line after the call that produced the error, here and line 1178. 
I think there is already a linting rule for that, but I have most of them disabled at the moment. You know, the original code is not super great.

2022-12-10 21:55 UTC, wbpascal commented
So this kind of opened another can of worms because I remembered that source VMs may use multiple different datastores (of which only some may be shared while others may not). Therefore to properly decide if the workaround needs to be used, all datastores used in the source VM have to be iterated over.

Also it is probably in our interest to not move any disks to different storages until we absolutely have to (e.g. disks that are already on a shared storage), so I modified the workaround to not use specific target datastores where possible. This should work in most cases, except in some where local datastores may differ between nodes. I have documented this case and how to work around it.

This also means that the `temp_datastore_id` argument is no longer necessary.

2022-12-10 22:01 UTC, wbpascal commented on proxmoxtf/resource_virtual_environment_vm.go
> +			err = veClient.MigrateVM(ctx, cloneNodeName, vmID, migrateBody, cloneTimeout)
My local linter says that this is an `ineffectual assignment to err`. I don't get this because if I understand this linter error correctly, it indicates that `err` is definitely overwritten after this assignment before it is read the next time (the `if` in line 1232). I can't see how this is possible. Can you please help me with this @bpg?

2022-12-11 16:32 UTC, bpg commented on proxmoxtf/resource_virtual_environment_vm.go
> +			err = veClient.MigrateVM(ctx, cloneNodeName, vmID, migrateBody, cloneTimeout)
this means value of err` is not used/checked. Just add
```go
	if err != nil {
		return diag.FromErr(err)
	}
```
and it should be good to go.

2022-12-12 20:29 UTC, wbpascal commented
I think I have fixed every outstanding issue now. Could you please take another look when you have time, @bpg?

2022-12-12 21:24 UTC, bpg approved these changes

2022-12-12 21:28 UTC, merged