fix(vm): Add parser for CustomEFIDisk
bpg/terraform-provider-proxmox pull request #208
Opened 2023-01-16 08:49 UTC by kaje783

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Add parser to use efi disk for UEFI 

Fix for [#202](https://github.com/bpg/terraform-provider-proxmox/issues/202)

2023-01-16 22:24 UTC, bpg requested changes
Thank again @kaje783! 👍🏻 

Just a minor feedback about the size parsing.

2023-01-16 22:24 UTC, bpg commented on proxmox/virtual_environment_vm_types.go
> +				iv, err := strconv.Atoi(size)
I think it would be better to use `parseDiskSize(string)` from `utils.go`, for consistency.
```suggestion
				iv, err := parseDiskSize(v[1])
```

2023-01-17 08:21 UTC, kaje783 commented
@bpg the function `parseDiskSize(&string)` is much better for this, i have changed it. 
Thanks.

2023-01-18 03:55 UTC, bpg approved these changes
Cool, I've added unit tests for the func and refactored the code a bit to address linter errors and remove duplication.

LGTM! 🚀

2023-01-18 03:57 UTC, merged