feat(vm): add support for 'boot_order and boot_disk flags for VM
bpg/terraform-provider-proxmox pull request #219
Opened 2023-01-24 06:14 UTC by HenriAW

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #214 

`boot_order` and `boot_disk` flags added to the VM resource. These are passed to the `boot` and `bootdisk` parameters in the Proxmox VE API described [here](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config).

2023-01-24 06:32 UTC, bpg commented
Hey @HenriAW, thanks for the PR!
I'll take a closer look later this week.

2023-01-29 18:21 UTC, bpg requested changes
Hey @HenriAW ! 👋🏻  
Thanks again for the PR!
I'd like to make a few changes to align it better with the PVE API and the existing code, please see my comments.

If you have any questions, feel free to toss them in, I'll be happy to discuss 🙂

2023-01-29 18:21 UTC, bpg-dev commented on proxmoxtf/resource_virtual_environment_vm.go
> +				Default:     dvResourceVirtualEnvironmentVMBootOrder,
Per [documentation](https://pve.proxmox.com/pve-docs/chapter-qm.html#qm_options), the boot order is specified as a comma-separate list, so I'd like to reflect that in the schema as well, i.e. to have something like:
```suggestion
				Type:        schema.TypeList,
				Description: "Specify the guest boot order",
				Optional:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Default:     dvResourceVirtualEnvironmentVMBootOrder,
```

This would also require adding a logic to convert from a list to a string and back. VM tags can be taken as an example as they are processed in a similar way.

2023-01-29 18:21 UTC, bpg-dev commented on proxmoxtf/resource_virtual_environment_vm.go
> +				Default:     dvResourceVirtualEnvironmentVMBootOrder,
You would also need to read the boot order back from PVE to populate the current state. It is usually done in [`resourceVirtualEnvironmentVMReadPrimitiveValues`](https://github.com/bpg/terraform-provider-proxmox/blob/2967218a1bbaf90f23bdb8c0c20d9465981542e4/proxmoxtf/resource_virtual_environment_vm.go#L3758) for values that referenced as [primitives](https://github.com/bpg/terraform-provider-proxmox/blob/b539aab22851817aea981727eb27a8da73edcc43/proxmox/virtual_environment_vm_types.go#L238) in the API model. Also keep in mind that we need to read from the "order" property of "boot" value returned by the PVE API.

2023-01-29 18:21 UTC, bpg commented on docs/resources/virtual_environment_vm.md
> +- `boot_order` - (Optional) Specify the guest boot order (defaults to `c`).
I think you're referring to the "legacy" parameter of the boot order which specifies a disk by its letter. We should probably switch to the device names: https://pve.proxmox.com/pve-docs/chapter-qm.html#qm_options

2023-04-07 19:34 UTC, bpg approved these changes

2023-04-07 19:35 UTC, merged