fix(vm): ignore ssd disk flag with virtio interface
bpg/terraform-provider-proxmox pull request #231
Opened 2023-02-06 21:10 UTC by abdo-farag

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

2023-02-06 22:05 UTC, bpg requested changes
Hey @abdo-farag! Thanks for the PR!

I have couple of comments, could you take a look pls?

2023-02-06 22:05 UTC, bpg-dev commented on Makefile
> -VERSION=0.12.0 # x-release-please-version
could you please revert this change?

2023-02-06 22:05 UTC, bpg commented on proxmoxtf/resource_virtual_environment_vm.go
> +        if strings.Contains(diskInterface, "scsi") {
From the PVE docs:
> Note that SSD emulation is not supported on VirtIO Block drives.

so I think this should be reflected in the condition then, i.e. `if !strings.HasPrefix(diskInterface, 'virtio') {...}`.

Also linter doesn't like cobbling `if` statements with unrelated assignments, so you may want to move this `if` block down a little bit, after the line 2494

2023-02-06 23:01 UTC, abdo-farag commented on Makefile
> -VERSION=0.12.0 # x-release-please-version
Hi @bpg 

This space makes some problems with me when building on Linux with zsh.
So when I run init with this space I get error.
``` terraform init``` 
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider bpg/proxmox: provider registry.terraform.io/bpg/proxmox was not found in any of the search locations

It's wierd somehow. but anyway if it bother you I will remove it.

2023-02-07 00:18 UTC, bpg commented on Makefile
> -VERSION=0.12.0 # x-release-please-version
Hmmm, that's interesting. My guess is when you run `make` it sets `VERSION` exactly to `0.12.0 # x-release-please-version` 🤦🏻
Good find, I'll take a look.

2023-02-07 00:19 UTC, bpg approved these changes

2023-02-07 00:19 UTC, merged